# Generated by Django 5.1.5 on 2025-07-22 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='f_creacion',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='f_termino',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
