# Generated by Django 5.1.5 on 2025-07-22 19:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('session', '0002_alter_task_f_creacion_alter_task_f_termino'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='f_creacion',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='task',
            old_name='f_termino',
            new_name='fecha_termino',
        ),
    ]
